-- Source: mo_population_table.sql
-- Added: 2026-01-29
-- Type: Code Reference - MO Population Table Implementation
-- Description: Creates the final MO population table with lookback suppressions
-- Output Table: GROWTH.MECHANIZED_OUTREACH_POPULATION

INSERT INTO {{ params.schema }}.MECHANIZED_OUTREACH_POPULATION_V2_SNAPSHOT
(
{{params.columns}}, RUN_DT
)
SELECT {{params.columns}}, CURRENT_TIMESTAMP() RUN_DT FROM {{ params.schema }}.MECHANIZED_OUTREACH_POPULATION;

INSERT OVERWRITE INTO {{ params.schema }}.MECHANIZED_OUTREACH_POPULATION (
	{{params.columns}}
)

WITH recent_accounts AS (
    SELECT max(run_dt) max_run_dt
    FROM PROD_RIPPLING_DWH.GROWTH.MASTER_DOMAIN_SOURCES
),
recent_master_accounts AS (
    SELECT DISTINCT
    a.NAME, SALESFORCE_ACCOUNT_ID, SALESFORCE_RED_ID, OUTREACH_ID, DOMAIN, EE_SIZE, EE_GROWTH, a.INDUSTRY, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, COUNTRY, POSTAL_CODE,
    HEADQUARTERS_CITY, HEADQUARTERS_STATE, HEADQUARTERS_COUNTRY, FOUNDED_YEAR, LAST_FUNDRAISE_DATE, FUNDING_ROUND, MOST_RECENT_VALUATION_USD, INVESTORS, TECHNOLOGIES,
    DOMAIN_SOURCE_DATES, ALL_INTL_EMPLOYEES,
    INTL_JOBS_POSTED['Australia'] AS AUS_JOBS_POSTED,
    INTL_EMPLOYEES['Australia'] AS AUS_EMPLOYEES,
    INTL_EMPLOYEE_GROWTH['Australia'] AS AUS_EMPLOYEE_GROWTH,
    INTL_JOBS_POSTED['Canada'] AS CAN_JOBS_POSTED,
    INTL_EMPLOYEES['Canada'] AS CAN_EMPLOYEES,
    INTL_EMPLOYEE_GROWTH['Canada'] AS CAN_EMPLOYEE_GROWTH,
    INTL_JOBS_POSTED['Germany'] AS DEU_JOBS_POSTED,
    INTL_EMPLOYEES['Germany'] AS DEU_EMPLOYEES,
    INTL_EMPLOYEE_GROWTH['Germany'] AS DEU_EMPLOYEE_GROWTH,
    INTL_JOBS_POSTED['France'] AS FRA_JOBS_POSTED,
    INTL_EMPLOYEES['France'] AS FRA_EMPLOYEES,
    INTL_EMPLOYEE_GROWTH['France'] AS FRA_EMPLOYEE_GROWTH,
    INTL_JOBS_POSTED['United Kingdom'] AS GBR_JOBS_POSTED,
    INTL_EMPLOYEES['United Kingdom'] AS GBR_EMPLOYEES,
    INTL_EMPLOYEE_GROWTH['United Kingdom'] AS GBR_EMPLOYEE_GROWTH,
    INTL_JOBS_POSTED['India'] AS IND_JOBS_POSTED,
    INTL_EMPLOYEES['India'] AS IND_EMPLOYEES,
    INTL_EMPLOYEE_GROWTH['India'] AS IND_EMPLOYEE_GROWTH,
    HIGH_CONFIDENCE_GLOBAL,
    LOW_CONFIDENCE_GLOBAL,
    DOMAIN_LAST_FORM_FILL_DATE_TIME_C,
    opp.NUMBER_OF_EMPLOYEES AS DWH_OPP_EE_SIZE,
    CASE
        WHEN acct.BILLING_COUNTRY = 'United States' THEN 'US'
        WHEN acct.BILLING_COUNTRY = 'Canada' THEN 'CA'
        WHEN acct.BILLING_COUNTRY = 'United Kingdom' THEN 'GB'
        WHEN acct.BILLING_COUNTRY = 'Australia' THEN 'AU'
        WHEN acct.BILLING_COUNTRY = 'France' then 'FR'
        ELSE acct.BILLING_COUNTRY
    END AS SFDC_ACCOUNT_BILLING_COUNTRY,
    LATEST_DOMAIN_WEBINAR_DATE,
    DOMAIN_NEW_RECYCLED_STATUS,
    GLOBAL_INTENT_SIGNAL,
    INTENT_CAMPAIGN,
    DOMAIN_SOURCE_DATES AS DOMAIN_REFRESH_DATES,
    LENGTH(
       CONCAT(DOMAIN, a.INDUSTRY, ADDRESS_LINE1, ADDRESS_LINE2, CITY, STATE, COUNTRY, POSTAL_CODE, HEADQUARTERS_CITY, HEADQUARTERS_STATE, HEADQUARTERS_COUNTRY, LAST_FUNDRAISE_DATE, FUNDING_ROUND, TO_VARCHAR(DOMAIN_SOURCE_DATES))
    ) AS ROW_LEN,
    a.COMPANY_SEGMENT,
    a.GROWTH_TIER
    FROM PROD_RIPPLING_DWH.GROWTH.MASTER_DOMAIN_SOURCES a
    JOIN recent_accounts ON a.run_dt = recent_accounts.max_run_dt
    LEFT JOIN PROD_RIPPLING_DWH.SFDC.RELATED_EMAIL_DOMAIN_C red ON SALESFORCE_RED_ID = red.ID
    LEFT JOIN PROD_RIPPLING_DWH.SFDC.ACCOUNT acct ON red.ACCOUNT_C = acct.ID
    LEFT JOIN DWH.OPPORTUNITIES opp ON opp.ACCOUNT_ID = red.ACCOUNT_C
),
master_accounts AS (
    SELECT *
    FROM recent_master_accounts
    qualify row_number() OVER (PARTITION BY DOMAIN ORDER BY (EE_SIZE, EE_GROWTH, ROW_LEN) DESC) = 1
),
recent_leads AS (
    SELECT max(run_dt) max_run_dt
    FROM PROD_RIPPLING_DWH.GROWTH.MASTER_MECH_OUTREACH_LEADS
),
master_leads AS (
    SELECT *
    FROM GROWTH.MASTER_MECH_OUTREACH_LEADS l
    JOIN recent_leads ON l.run_dt = recent_leads.max_run_dt
    WHERE NVL(IS_RECORD_SUPPRESSED, FALSE) = FALSE
)
,OUTREACH_LEADS_LAST_30_DAYS AS (
    SELECT pe.EMAIL
    FROM OUTREACH.PROSPECT p
    LEFT JOIN OUTREACH.PROSPECT_EMAIL pe ON p.ID = pe.PROSPECT_ID
    WHERE pe.EMAIL IS NOT NULL
    AND (
        (
            p.TOUCHED_AT IS NOT NULL
            AND
            p.TOUCHED_AT > DATEADD(day, -30, CURRENT_DATE())
        )
        OR
        (   p.ENGAGED_AT IS NOT NULL
            AND
            p.ENGAGED_AT > DATEADD(day, -30, CURRENT_DATE())
        )
    )
)
, OUTREACH_LEADS_LAST_60_DAYS AS (
    SELECT pe.EMAIL
    FROM OUTREACH.PROSPECT p
    LEFT JOIN OUTREACH.PROSPECT_EMAIL pe ON p.ID = pe.PROSPECT_ID
    WHERE pe.EMAIL IS NOT NULL
    AND (
        (
            p.TOUCHED_AT IS NOT NULL
            AND
            p.TOUCHED_AT > DATEADD(day, -60, CURRENT_DATE())
        )
        OR
        (   p.ENGAGED_AT IS NOT NULL
            AND
            p.ENGAGED_AT > DATEADD(day, -60, CURRENT_DATE())
        )
    )
)
, OUTREACH_LEADS_LAST_90_DAYS AS (
    SELECT pe.EMAIL
    FROM OUTREACH.PROSPECT p
    LEFT JOIN OUTREACH.PROSPECT_EMAIL pe ON p.ID = pe.PROSPECT_ID
    WHERE pe.EMAIL IS NOT NULL
    AND (
        (
            p.TOUCHED_AT IS NOT NULL
            AND
            p.TOUCHED_AT > DATEADD(day, -90, CURRENT_DATE())
        )
        OR
        (   p.ENGAGED_AT IS NOT NULL
            AND
            p.ENGAGED_AT > DATEADD(day, -90, CURRENT_DATE())
        )
    )
)
, dsar_compliance_leads AS (
    SELECT EMAIL
    FROM SFDC.LEAD
    WHERE DSAR_COMPLIANCE_FLAG_C = TRUE
    AND EMAIL IS NOT NULL
),
neverbounce_invalidated_leads AS (
    SELECT EMAIL
    FROM GROWTH.MASTER_EMAIL_VALIDATION_DATA
    WHERE EMAIL_VALID_NEVERBOUNCE = FALSE
    AND EMAIL IS NOT NULL
),
automated_intent_leads AS (
    SELECT EMAIL
    FROM GROWTH.MASTER_LSW_INTENT_LEADS
    WHERE LEAD_PROCESSED = TRUE
    AND LEAD_SUPPRESSED = FALSE
    AND EMAIL IS NOT NULL
)
, PERSONALIZATION_STATUS AS (
    SELECT EMAIL,
        DATE(SPLIT_PART(UNIQUE_TOKEN, '_', 1)) AS SUB_DATE, PERSONALIZATION_STATUS
    FROM PROD_RIPPLING_DWH.GROWTH.PERSONALIZATION_STATUS
    QUALIFY ROW_NUMBER() OVER (PARTITION BY EMAIL ORDER BY SUB_DATE DESC) = 1
)
, LEAD_SEQUENCE_COUNT as (
SELECT
    COUNT(*) AS SEQUENCE_COUNT,
    DATA_CONNECTION.ID AS LEAD_ID
FROM
    PROD_RIPPLING_DWH.OUTREACH.SEQUENCE_STATE
    LEFT JOIN PROD_RIPPLING_DWH.OUTREACH.DATA_CONNECTION
        ON SEQUENCE_STATE.RELATIONSHIP_PROSPECT_ID = DATA_CONNECTION.PARENT_ID
        AND DATA_CONNECTION.TYPE IN ('Lead', 'Contact')
        AND DATA_CONNECTION.ID NOT IN (
            SELECT ID FROM PROD_RIPPLING_DWH.SFDC.LEAD WHERE LEAD.IS_CONVERTED = TRUE
        )
    LEFT JOIN PROD_RIPPLING_DWH.OUTREACH.SEQUENCE_TAG
        ON SEQUENCE_STATE.RELATIONSHIP_SEQUENCE_ID = SEQUENCE_TAG.SEQUENCE_ID
        AND SEQUENCE_TAG.TAG_NAME = 'Cold Outbound'
    WHERE
        SEQUENCE_STATE.DELIVER_COUNT >= 1
        AND SEQUENCE_TAG.TAG_NAME = 'Cold Outbound'
    GROUP BY
        LEAD_ID
)
SELECT
master_leads.SALESFORCE_ID AS LEAD_SALESFORCE_ID, master_leads.OUTREACH_ID AS LEAD_OUTREACH_ID, master_leads.SALESFORCE_ID AS SALESFORCE_ID, master_accounts.SALESFORCE_RED_ID, master_leads.SFDC_OBJECT_TYPE AS SALESFORCE_OBJECT_TYPE,
master_leads.FIRST_NAME, master_leads.LAST_NAME, master_leads.TITLE, master_leads.PERSONA, master_leads.EMAIL, master_leads.EXPERIMENT, master_leads.NEW_RECYCLED_STATUS, master_leads.PERSONALIZED_SENTENCE_1, master_leads.PERSONALIZED_SENTENCE_2,
COALESCE(SFDC_ACCOUNT_BILLING_COUNTRY, master_accounts.HEADQUARTERS_COUNTRY, master_leads.HQ_COUNTRY) AS COUNTRY,
COALESCE(master_accounts.HEADQUARTERS_STATE, master_leads.HQ_REGION) AS REGION,
COALESCE(master_accounts.HEADQUARTERS_CITY, master_leads.HQ_CITY) AS CITY,
master_leads.HQ_COUNTRY AS PERSON_COUNTRY,
master_leads.HQ_REGION AS PERSON_REGION,
master_leads.HQ_CITY AS PERSON_CITY,
COALESCE(master_accounts.ADDRESS_LINE1, master_leads.HQ_STREET_ADDRESS) AS STREET_ADDRESS_1,
master_accounts.ADDRESS_LINE2 AS STREET_ADDRESS_2, master_leads.EMAIL_SOURCE, master_leads.LINKEDIN_URL, master_leads.DOMAIN,
COALESCE(master_accounts.NAME, master_leads.COMPANY_NAME) AS COMPANY_NAME,
master_leads.JOB_CHANGE, master_leads.JOB_CHANGE_DATE, master_leads.JOB_PROMOTION, master_leads.JOB_PROMOTION_DATE,
CASE
    WHEN master_accounts.DOMAIN_SOURCE_DATES['PRIMER_LEADS'] IS NOT NULL THEN True
    ELSE False
END AS ACCOUNT_JOB_CHANGE_FLAG,
master_leads.IS_PARTNER_ACCOUNT PARTNER, COALESCE(master_accounts.SALESFORCE_ACCOUNT_ID, master_accounts.SALESFORCE_RED_ID) AS ACCOUNT_SALESFORCE_ID, master_accounts.OUTREACH_ID AS ACCOUNT_OUTREACH_ID,
COALESCE(master_accounts.EE_SIZE, DWH_OPP_EE_SIZE, master_leads.EE_SIZE) AS EE_SIZE,
master_accounts.EE_GROWTH, COALESCE(master_accounts.INDUSTRY, LEAD.INDUSTRY), master_leads.INDUSTRY_SEGMENT,
master_accounts.POSTAL_CODE, master_accounts.FOUNDED_YEAR, master_accounts.LAST_FUNDRAISE_DATE,
master_accounts.FUNDING_ROUND, master_accounts.MOST_RECENT_VALUATION_USD, master_accounts.INVESTORS, master_accounts.TECHNOLOGIES, ALL_INTL_EMPLOYEES,
AUS_JOBS_POSTED, AUS_EMPLOYEES, AUS_EMPLOYEE_GROWTH, CAN_JOBS_POSTED, CAN_EMPLOYEES, CAN_EMPLOYEE_GROWTH, DEU_JOBS_POSTED, DEU_EMPLOYEES, DEU_EMPLOYEE_GROWTH, FRA_JOBS_POSTED, FRA_EMPLOYEES, FRA_EMPLOYEE_GROWTH, GBR_JOBS_POSTED, GBR_EMPLOYEES, GBR_EMPLOYEE_GROWTH, IND_JOBS_POSTED, IND_EMPLOYEES, IND_EMPLOYEE_GROWTH,
master_leads.CLOSED_LOST_DATE AS CLOSED_LOST_DATE,
master_leads.IS_ON_OPPORTUNITY AS IS_ON_OPPORTUNITY,
master_leads.LAST_STAGE_BEFORE_CLOSE AS LAST_STAGE_BEFORE_CLOSE,
master_leads.CLOSED_LOST_ACCOUNT_SEGMENT AS CLOSED_LOST_ACCOUNT_SEGMENT,
master_leads.FUTURE_CONTACT_DATE AS FUTURE_CONTACT_DATE,
HIGH_CONFIDENCE_GLOBAL, LOW_CONFIDENCE_GLOBAL,
LAST_FORM_FILL_DATE_TIME_C, DOMAIN_LAST_FORM_FILL_DATE_TIME_C,
LAST_ACTIVITY_DATE, ADDED_TO_SEQUENCE, COMPANY_START_DATE, POSITION_START_DATE,
master_leads.LAST_INBOUND_CONTENT_FF_C, master_leads.LAST_INBOUND_CONTENT_FF_DATE_TIME_C,
COUNT(master_leads.EMAIL) OVER (PARTITION BY master_leads.DOMAIN) AS DOMAIN_LEAD_COUNT,
master_leads.EMAIL_NVRB_VALIDATED_TS AS EMAIL_NVRB_VALIDATED_TS,
CASE
    WHEN LAST_FUNDRAISE_DATE IS NOT NULL AND FUNDING_ROUND != 'grant' THEN TRUE
    ELSE FALSE
END AS VC_BACKED_TECH,
CASE
    WHEN EE_GROWTH < 0 THEN 'NEGATIVE_GROWTH'
    WHEN EE_GROWTH >= 0 AND EE_GROWTH < 0.15 THEN 'LOW_GROWTH'
    WHEN EE_GROWTH >= 0.15 THEN 'HIGH_GROWTH'
    ELSE NULL
END AS EE_GROWTH_BUCKET,
NULL LATEST_WEBINAR_DATE, NULL LATEST_DOMAIN_WEBINAR_DATE, DOMAIN_NEW_RECYCLED_STATUS,
GLOBAL_INTENT_SIGNAL, master_accounts.INTENT_CAMPAIGN, master_accounts.DOMAIN_REFRESH_DATES,
CASE
    WHEN master_leads.EMAIL IN (SELECT EMAIL FROM automated_intent_leads) THEN TRUE
    ELSE FALSE
END AS INTENT,

CASE
    WHEN OUTREACH_LEADS_LAST_30_DAYS.EMAIL IS NOT NULL
    OR (master_leads.LAST_ACTIVITY_DATE IS NOT NULL AND master_leads.LAST_ACTIVITY_DATE > CURRENT_DATE() - 30)
    OR (master_leads.ADDED_TO_SEQUENCE IS NOT NULL and master_leads.ADDED_TO_SEQUENCE > CURRENT_DATE() - 30)
THEN TRUE ELSE FALSE END THIRTY_DAY_LOOKBACK_SUPPRESSION,

CASE
    WHEN OUTREACH_LEADS_LAST_60_DAYS.EMAIL IS NOT NULL
    OR (master_leads.LAST_ACTIVITY_DATE IS NOT NULL AND master_leads.LAST_ACTIVITY_DATE > CURRENT_DATE() - 60)
    OR (master_leads.ADDED_TO_SEQUENCE IS NOT NULL and master_leads.ADDED_TO_SEQUENCE > CURRENT_DATE() - 60)
THEN TRUE ELSE FALSE END SIXTY_DAY_LOOKBACK_SUPPRESSION,

CASE
    WHEN OUTREACH_LEADS_LAST_90_DAYS.EMAIL IS NOT NULL
    OR (master_leads.LAST_ACTIVITY_DATE IS NOT NULL AND master_leads.LAST_ACTIVITY_DATE > CURRENT_DATE() - 90)
    OR (master_leads.ADDED_TO_SEQUENCE IS NOT NULL and master_leads.ADDED_TO_SEQUENCE > CURRENT_DATE() - 90)
THEN TRUE ELSE FALSE END NINETY_DAY_LOOKBACK_SUPPRESSION,

CASE
    WHEN LAST_FORM_FILL_DATE_TIME_C IS NULL AND LAST_INBOUND_CONTENT_FF_DATE_TIME_C IS NULL
    THEN FALSE ELSE TRUE END
INCLUDE_RECYCLED_INBOUND_LEADS,


CASE
    WHEN CLOSED_LOST_DATE IS NOT NULL AND CURRENT_DATE() - CLOSED_LOST_DATE > 90
THEN TRUE ELSE FALSE END ONLY_INCLUDE_DOMAINS_CLOSED_LOST_MORE_THAN_90_DAYS_BEFORE,

CASE
    WHEN CLOSED_LOST_DATE IS NOT NULL AND CURRENT_DATE() - CLOSED_LOST_DATE < 90
THEN TRUE ELSE FALSE END ONLY_INCLUDE_DOMAINS_CLOSED_LOST_IN_LAST_90_DAYS,

PERSONALIZATION_STATUS.PERSONALIZATION_STATUS AS PERSONALIZATION_STATUS,
LEAD_SEQUENCE_COUNT.SEQUENCE_COUNT AS COLD_OUTBOUND_SEQUENCE_COUNT,

master_leads.PEO_PROVIDER_C,
master_leads.PEO_PROVIDER_LAST_UPDATED_C,

master_leads.IS_ELIGIBLE_FOR_RANKING,
master_leads.JOB_FUNCTION_PREDICTION,
master_leads.SENIORITY_PREDICTION,
master_leads.LIKELY_GLOBAL_FIT,
master_accounts.COMPANY_SEGMENT,
master_accounts.GROWTH_TIER
FROM master_leads
LEFT JOIN master_accounts ON master_leads.DOMAIN = master_accounts.DOMAIN
LEFT JOIN (select id, industry from SFDC.LEAD) LEAD on master_leads.salesforce_id = LEAD.ID
LEFT JOIN OUTREACH_LEADS_LAST_30_DAYS on OUTREACH_LEADS_LAST_30_DAYS.email = master_leads.email
LEFT JOIN OUTREACH_LEADS_LAST_60_DAYS on OUTREACH_LEADS_LAST_60_DAYS.email = master_leads.email
LEFT JOIN OUTREACH_LEADS_LAST_90_DAYS on OUTREACH_LEADS_LAST_90_DAYS.email = master_leads.email
LEFT JOIN PERSONALIZATION_STATUS ON PERSONALIZATION_STATUS.EMAIL = master_leads.EMAIL
LEFT JOIN LEAD_SEQUENCE_COUNT ON LEAD_SEQUENCE_COUNT.LEAD_ID = master_leads.SALESFORCE_ID

WHERE master_leads.EMAIL NOT IN (SELECT EMAIL FROM dsar_compliance_leads)
AND master_leads.EMAIL NOT IN (SELECT EMAIL FROM neverbounce_invalidated_leads)
AND NOT CONTAINS(master_leads.DOMAIN, '.edu')
AND (NVL(master_leads.HQ_COUNTRY, '') != 'DE' AND COALESCE(SFDC_ACCOUNT_BILLING_COUNTRY, master_accounts.HEADQUARTERS_COUNTRY, master_leads.HQ_COUNTRY, '') NOT IN ('DE', 'Germany')) -- exclude leads from Germany for legal compliance
-- AND (REGION IS NULL OR REGION <> 'HI')
QUALIFY ROW_NUMBER() OVER(
    PARTITION BY master_leads.EMAIL
    ORDER BY CASE WHEN master_leads.SFDC_OBJECT_TYPE = 'CONTACT' THEN 1 ELSE 2 END ASC, master_leads.RUN_DT DESC
) = 1;
